lsi: false
safe: true
source: https://github.com/tyfa7215/hw_01/tree/gh-pages
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
